server:
  port: 0

spring:
  application:
    name: leave-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payrolldb
    username: postgres
    password: TITAN@0one
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

management:
  endpoints:
    web:
      exposure:
        include: "*"
